name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: epinero-weather-app
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup.NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Start SQL Server 🐳
        run: |
          docker run -d -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=pass~w0rD!" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest

      - name: Sleep for 5 seconds 😴
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Restore
        run: dotnet restore ./MilanCiCdExample.sln
        
      - name: Build
        run: dotnet build ./MilanCiCdExample.sln -c Release --no-restore

      - name: Run automated tests 🧪
        env:
          ConnectionStrings__DefaultConnection: Server=localhost;Database=PokemonDatabase_Test;User=sa;Password=pass~w0rD!
        run: dotnet test ./MilanCiCdExample.sln -c Release --no-build

      - name: Publish
        run: dotnet publish ./MilanCiCdExample.sln -c Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
     
      - name: Deployment 🚀
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
