name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: epinero-weather-app
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup.NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./MilanCiCdExample.sln
        
      - name: Build
        run: dotnet build ./MilanCiCdExample.sln -c Release --no-restore

      - name: Run automated tests 🧪
        run: dotnet test ./MilanCiCdExample.sln -c Release --no-build

      - name: Publish
        run: dotnet publish ./MilanCiCdExample.sln -c Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
     
      - name: Deployment 🚀
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
